require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConfessionsController do

  # This should return the minimal set of attributes required to create a valid
  # Confession. As you add validations to Confession, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConfessionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end
  
  ### Andrews specs
  ### END Andrews specs
  

  describe "GET index" do
    it "assigns all confessions as @confessions" do
      confession = Confession.create! valid_attributes
      get :index, {}, valid_session
      assigns(:confessions).should eq([confession])
    end
  end

  describe "GET show" do
    it "assigns the requested confession as @confession" do
      confession = Confession.create! valid_attributes
      get :show, {:id => confession.to_param}, valid_session
      assigns(:confession).should eq(confession)
    end
  end

  describe "GET new" do
    it "assigns a new confession as @confession" do
      get :new, {}, valid_session
      assigns(:confession).should be_a_new(Confession)
    end
  end

  describe "GET edit" do
    it "assigns the requested confession as @confession" do
      confession = Confession.create! valid_attributes
      get :edit, {:id => confession.to_param}, valid_session
      assigns(:confession).should eq(confession)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Confession" do
        expect {
          post :create, {:confession => valid_attributes}, valid_session
        }.to change(Confession, :count).by(1)
      end

      it "assigns a newly created confession as @confession" do
        post :create, {:confession => valid_attributes}, valid_session
        assigns(:confession).should be_a(Confession)
        assigns(:confession).should be_persisted
      end

      it "redirects to the created confession" do
        post :create, {:confession => valid_attributes}, valid_session
        response.should redirect_to(Confession.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved confession as @confession" do
        # Trigger the behavior that occurs when invalid params are submitted
        Confession.any_instance.stub(:save).and_return(false)
        post :create, {:confession => {}}, valid_session
        assigns(:confession).should be_a_new(Confession)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Confession.any_instance.stub(:save).and_return(false)
        post :create, {:confession => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested confession" do
        confession = Confession.create! valid_attributes
        # Assuming there are no other confessions in the database, this
        # specifies that the Confession created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Confession.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => confession.to_param, :confession => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested confession as @confession" do
        confession = Confession.create! valid_attributes
        put :update, {:id => confession.to_param, :confession => valid_attributes}, valid_session
        assigns(:confession).should eq(confession)
      end

      it "redirects to the confession" do
        confession = Confession.create! valid_attributes
        put :update, {:id => confession.to_param, :confession => valid_attributes}, valid_session
        response.should redirect_to(confession)
      end
    end

    describe "with invalid params" do
      it "assigns the confession as @confession" do
        confession = Confession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Confession.any_instance.stub(:save).and_return(false)
        put :update, {:id => confession.to_param, :confession => {}}, valid_session
        assigns(:confession).should eq(confession)
      end

      it "re-renders the 'edit' template" do
        confession = Confession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Confession.any_instance.stub(:save).and_return(false)
        put :update, {:id => confession.to_param, :confession => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested confession" do
      confession = Confession.create! valid_attributes
      expect {
        delete :destroy, {:id => confession.to_param}, valid_session
      }.to change(Confession, :count).by(-1)
    end

    it "redirects to the confessions list" do
      confession = Confession.create! valid_attributes
      delete :destroy, {:id => confession.to_param}, valid_session
      response.should redirect_to(confessions_url)
    end
  end

end
